## ginked from https://github.com/pkg/json 1/15/23
## 
## agreeing with Mr. Cheney on disabled linters
## commented ones are mostly not generating hits
## Todo: try out on more code and settle dust
run:
  go: '1.21'

linters:
  enable-all: true
  disable:
    - asasalint
    #- bodyclose
    - containedctx
    - contextcheck
    #- cyclop
    - deadcode # replaced with unused
    - depguard # too annoying
    #- dupl
    #- dupword
    #- errcheck
    #- errchkjson
    #- errname
    #- errorlint
    - exhaustivestruct # Replaced by exhaustruct.
    - exhaustruct
    - exhaustive # too annoying, too hard to disable with comments
    #- forbidigo
    #- funlen
    - gci # maybe want this, pct
    - gochecknoglobals
    #- gocognit
    #- goconst
    - gocritic
    #- gocyclo
    - godot
    #- godox
    - goerr113
    - gofumpt
    - golint # Replaced by revive.
    - gomnd
    - ifshort
    - inamedparam # too opinionated
    - interfacer # deprecated
    #- ireturn
    - lll
    #- maintidx
    - maligned # Replaced by govet
    - musttag # flaky, fires on structs which aren't JSON marshalled
    - nakedret # pct
    #- nilnil
    - nlreturn
    #- noctx
    - nonamedreturns
    - nosnakecase # Replaced by revive, pct
    - paralleltest
    #- prealloc
    - scopelint # Replaced by exportloopref.
    - structcheck # replaced with unused
    - tagliatelle
    - tagalign # too fussy
    - testpackage # too annoying
    #- thelper
    - usestdlibvars
    - varcheck # Replaced by unused.
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  #gofumpt:
    #module-path: github.com/pkg/json
  revive:
    rules:
    - name: var-naming
      disabled: true
  stylecheck:
    checks: [
      "all",
      "-ST1003",
      "-ST1012"
    ]
  unparam:
    check-exported: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
